version: "3.3"

services:
  postgres:
    image: docker.io/timescale/timescaledb:2.17.2-pg16
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  grafana:
    image: docker.io/grafana/grafana:main
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  postgres-data: {}
  grafana-data: {}
